### ISSUE TITLE
I think incorrect processing of text

### ISSUE THREAD

**Issue by shahawi** [aelbuni/quran-nlp#2]
Al salamu alaikom,
I tried exporting the end result of the processing of the holy quran to a text file and this is what I got,
[your_file.txt](https://github.com/aelbuni/quran-nlp/files/3110310/your_file.txt)

> 
 بسم الله الرحمٰن الرحيم الحمد لله رب العالمين يوم الدين صراط عليهم ذٰلك الكتاب ريب هدى للمتقين يؤمنون الصلاة ينفقون أنزل قبلك أولٰئك علىٰ ربهم وأولٰئك كفروا سواء قلوبهم وعلىٰ ولهم عذاب عظيم الناس يقول آمنا بالله الآخر آمنوا أنفسهم يشعرون أليم كانوا قيل الأرض قالوا إنهم ولٰكن آمن يعلمون إلىٰ معكم فما نارا فلما فهم يرجعون السماء الموت ۚ والله أظلم شاء شيء قدير اعبدوا ربكم خلقكم قبلكم لعلكم تتقون جعل ماء رزقا وأنتم تعلمون كنتم صادقين ولن فاتقوا النار للكافرين وعملوا الصالحات جنات تجري تحتها الأنهار هٰذا قبل وهم خالدون مثلا فأما أنه الحق وأما أراد ۘ يضل كثيرا أمر إليه ترجعون خلق جميعا بكل عليم قال ربك إني ونحن أعلم آدم الملائكة فقال هٰؤلاء علم إنك العليم الحكيم ألم السماوات والأرض وكان الكافرين الجنة هٰذه الظالمين الشيطان عنها بعضكم عدو ولكم ربه خوف بآياتنا أصحاب بني إسرائيل عليكم تكونوا أول قليلا وآتوا الزكاة أنفسكم أفلا تعقلون أنهم واتقوا يوما نفس شيئا آل فرعون سوء العذاب وفي ذٰلكم البحر موسىٰ بعده عنكم تشكرون آتينا موسى قوم إنكم خير حتىٰ كلوا يظلمون المحسنين ظلموا قولا واحد يخرج بأنهم بآيات بغير وكانوا واليوم صالحا فضل ولقد منكم يبين إنها علينا وإنا بالحق كذٰلك يحيي الموتىٰ آياته أشد الماء تعملون وقد كان منهم يسمعون بعضهم يعلم ومنهم للذين يقولون أيديهم وقالوا قل فلن بلىٰ فأولٰئك تعبدون للناس حسنا ببعض جزاء يفعل الحياة الدنيا ويوم القيامة بالآخرة عنهم ابن مريم جاءكم رسول ولما جاءهم كتاب ينزل فضله يشاء عباده فلم مؤمنين بالبينات سمعنا كانت الآخرة أبدا قدمت بصير يعملون فإنه بإذن يديه وهدى للمؤمنين أنزلنا آيات بينات يكفر أكثرهم أوتوا ملك كفر أحد فتنة لمن تقولوا أهل المشركين العظيم آية ولي فقد ضل السبيل يأتي مثل يحكم بينهم ولله تولوا اتخذ أمرا فإنما وقال قبلهم الآيات لقوم الجحيم الهدىٰ ولئن العلم آتيناهم حق إبراهيم جعلنا وبئس المصير ربنا منا السميع أمة فيهم رسولا العزيز نفسه وإنه الصالحين إلٰها خلت كسبت إلينا أحسن عنده عليها يهدي مستقيم وكذٰلك الرسول شهيدا كنت رحيم المسجد الحرام يكون أرسلنا آياتنا سبيل ورحمة جناح خيرا وأنا أجمعين خالدين ينظرون إلٰه الليل والنهار لآيات يعقلون وأن شديد أعمالهم مبين أولو حرم عاد غفور بأن نزل لفي البر كتب بالمعروف أولي الألباب حقا المتقين سميع أيام وعلى فهو القرآن يريد لعلهم يتقون بينكم يحب تكون واعلموا يكن العقاب قبله حسنة كسبوا الحساب جهنم عزيز حكيم يأتيهم الأمر وإلى نعمة اتقوا واحدة جاءتهم معه شر أكبر والآخرة يؤمن يدعون النساء أنىٰ المؤمنين أيمانكم الظالمون خبير متاع تر وإليه الملك ولم لآية اليوم القوم ولولا المرسلين الرسل بعدهم ربي قرية أولم أموالهم جنة وله نار مغفرة يستطيعون ورسوله أجل مسمى كبيرا التوراة رحمة كذبوا فقل وقل يفترون فكيف النهار المؤمنون أولياء تجد قالت الذكر واذكر الغيب ولد بشر أني إلي فوق عذابا تكن لهو كلمة بيننا وهٰذا النبي طائفة ويقولون إليهم قوما سبيلا تتلىٰ وجوههم الصدور يغفر أجر عاقبة أمرنا قلوب أفمن لقد ضلال وقيل يومئذ يجعل أنما كذب عمل ذكر ملكت وكفىٰ لكل عليما حكيما الفوز رحيما غفورا عظيما الإنسان فسوف عنه بينهما أهلها أجرا جاء بصيرا المنافقين علي ليقولن وعد كنا أخرىٰ القول دونه الكافرون فقالوا اتخذوا شك نوح وجعلنا نذير أحدا أخاف رسلنا أيمانهم وجعل فهل المبين الصادقين تأتيهم يروا أهلكنا آلهة كذبا الأولين الساعة كذبت تدعون سلام المجرمين الشمس قومه نشاء نجزي القرىٰ والقمر الجن عملوا تذكرون ربكما كافرون العرش رحمته الملأ الفلك آلاء الجبال عسىٰ وكنا خلقنا فبأي يشركون ۩ كريم قوة لوط يوسف تكذبان

I definitely think there is a huge problem with this sample.
I am sorry I am not proficient in machine learning but I don't think this could be right.

I exported using this code 

```
with open('your_file.txt', 'w') as f:
    for item in words:
        f.write(" "+item)
```

**Comment by aelbuni** [comment]
Salam Shahawi,

I don't think there is any issue with the machine constructed list of words you are printing. The list being crunched by a neural network model, which shouldn't make much sense for us.

You are writing the vocabulary words generated from training the word2vec model. So this list of words represent the frequently used words in a machine defined order. 

`words = list(model.wv.vocab)`

This `vocab` vector is what is been used to serve other core functions like:

model.[most_similar(one_word)](https://radimrehurek.com/gensim/models/keyedvectors.html#gensim.models.keyedvectors.WordEmbeddingsKeyedVectors.most_similar)

See [code](https://github.com/aelbuni/quran-nlp/blob/6e3b3df2eaf0dd06ab6e85ece6ef1557397e0da0/main.py#L78) to check how you can pass a Word to extract a context.

`vocabulary` [definition](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec)

`vocabulary` This object represents the vocabulary (sometimes called Dictionary in gensim) of the model. Besides keeping track of all unique words, this object provides extra functionality, such as constructing a huffman tree (frequent words are closer to the root), or discarding extremely rare words

**Documentation**
For more details about the Machine Learning Pipeline used, please read the following documentation:
https://medium.com/@aelbuni/modeling-topics-in-quran-using-machine-learning-nlp-b88ca23fb44d

**Comment by shahawi** [comment]
Thank you for your comprehensive answer I understand now.
